### ISSUE TITLE
Unexpected results of `transitivity`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#109]
Where does this formula for transitivity come from?

https://github.com/JuliaDynamics/RecurrenceAnalysis.jl/blob/2511090f56104f20416667124c4346407462057b/src/rqa.jl#L106-L108

I didn't find it in the cited papers, an it does not produce the same results as `global_clustering_coefficient` from LightGraphs.jl, although the concept cited in the docstring does coincide. (In case of doubt, I have tried with hand-made tiny examples, and the result of LightGraphs looks correct, but the output of `transitivity` here does not.)

To reproduce the inconsistency, try `SimpleGraph(R.data) |> global_clustering_coefficient` and compare with `transitivity(R)`.

(By the way, transitivity would normally be calculated with adjacency matrices that do not have elements in the diagonal - I am addressing that in the branch `graphs` - WIP)

**Comment by pucicu** [comment]
There is difference between clustering coeff. and transitivity coeff. As far as I remember, we have always used trans. coeff. but could have used the not-completely correct name clustering coeff.
(I would need to check)

**Comment by pucicu** [comment]
I have checked the papers. The formula of trans in the julia code is the same as in the referred papers. Why do you think that it is not?

As I said, the global clust. coeff. and the trans. coeff. are different. The global clust. coeff. is the average of the local clust. coeff., where the trans. is a global measure by definition. Just compare Eq. (10) with Eq. (11) in the paper R.V. Donner *et al.*, [The geometry of chaotic dynamics — a complex network perspective, Eur. Phys. J. B 84, 653–672 (2011)
You will see that for trans the ratio is formed with sums over i,j,k in both numerator and denominator whereas for glob. clust. the numerator is only a sum over j and k, and the global sum is created over the ratio.

Another more review like source to be considered could be
- Zou, R. V. Donner, N. Marwan, J. F. Donges, J. Kurths: Nonlinear time series analysis by means of complex networks, Scientia Sinica: Physica, Mechanica & Astronomica, 50(1), 010509 (2020). DOI:10.1360/SSPMA-2019-0136

**Comment by heliosdrm** [comment]
Thank you Norbert for the explanation on the differences. There is confusion with the nomenclature indeed. Anyway, I still think that there is a mistake in the formula. Take this adjacency matrix:

```julia
mat =  [0 1 0 1 0 0
        1 0 1 1 1 0
        0 1 0 0 0 0
        1 1 0 0 0 1
        0 1 0 0 0 1
        0 0 0 1 1 0]
```

It's small enough to draw the graph by hand and count: its corresponding graph has 12 linked triples of indices (the denominator of the transitivity coefficient), but only one triangle (connecting 1st, 2nd and 4th vertices), so the transitivity coefficient should be 3/12 = 0.25, according to Eq. (11)  of Donner et al. Now:

```julia
julia> using LightGraphs

julia> global_clustering_coefficient(SimpleGraph(mat))
0.25
```

But:
```julia
julia> using RecurrenceAnalysis

julia> transitivity(RecurrenceMatrix(mat))
0.15789473684210525 
```

I've found that the mistake is in the denominator, that lacks the trace of the squared matrix - or else I am still misunderstanding something:
```julia
julia> tr(mat^3)/sum(mat^2) # equivalent to current code
0.15789473684210525

julia> tr(mat^3)/(sum(mat^2) - tr(mat^2)) # with modified denominator
0.25
```

**Comment by pucicu** [comment]
Yes, you are right, the main diagonal has to be removed. I just realized that in the paper Zou et al, 2019, there is a mistake in the corresponding equation (it is also Eq. (11) in this paper). But in Donner et al, 2011, it is correctly given. In the julia code, the diagonal is still included in the denominator. You are right to substract tr(mat^2).

Sorry that I have overseen this.

**Comment by heliosdrm** [comment]
Ok, so let's clarify the whole issue. This is what I understood, please let me know if that's all right:

* The concept of "global clustering coefficient" can be defined in two ways:
    - As by Watts and Strogatz (1998), i.e. the average of local clustering coefficients.
    - As by Barrat and Weigt (2000), i.e. 3 × number of triangles divided by number of linked triples in the whole network.
* "Transitivity" specifically refers to Barrat's and Weigt's definition.
* Barrat's and Weigt's definition seems to be predominant, and there are places where "global clustering coefficient" is plainly taken as the same as transitivity, leaving Watt's and Strogatz's original definition as an "alternative" (remarkably in the [Wikipedia article](https://en.wikipedia.org/wiki/Clustering_coefficient#Global_clustering_coefficient), cf. also its [discussion page](https://en.wikipedia.org/wiki/Talk:Clustering_coefficient#Global_clustering_coefficient_vs._Transitivity_ratio)).
* LightGraphs.jl seems to take that view, such that its [code of `global_culstering_coefficient`](https://github.com/JuliaGraphs/LightGraphs.jl/blob/1c6cf65cc0981250e430bbef39055da23bd25bd0/src/community/clustering.jl#L143-L159) implements Barrat's and Weight's definition (i.e. the so-called transitivity, although it does not use that name).

If all that is correct, I'm afraid that the implementation and the docstring of `transitivity` in this package is quite a mess:
* The function name implies that it should implement Barrat's and Weigt's definition.
* However, the docstring seems to imply that it implements Watt's and Strogatz's definition (average of local clustering coefficient).
* Nevertheless, the formula that it uses looks like being meant to calculate Barrat's and Weigt's definition.
* But the denominator is wrong, so it doesn't calculate any of them!

Now, fixing the code of the function to give the correct result as by Barrat and Weigt is the easiest (just fix the denominator by subtracting the trace of `R²`). But what do we do about the rest?
* Modify the description given in the docstring, removing the reference to the average of local clustering coefficient and giving Barrat's and Weigt's definition instead?
* Give both definitions, and extend the function to allow the user choose between them?

Since we are planning to add the functions from LightGraphs.jl, as a quick fix while that is ready I'd suggest the simplest solution, i.e. the first one.

**Comment by Datseris** [comment]
i agree with first one.

**Comment by pucicu** [comment]
> Ok, so let's clarify the whole issue. This is what I understood, please let me know if that's all right:
> The concept of "global clustering coefficient" can be defined in two ways:
> As by Watts and Strogatz (1998), i.e. the average of local clustering coefficients.
> As by Barrat and Weigt (2000), i.e. 3 × number of triangles divided by number of linked triples in the whole network.

yes, but later the Barrat & Weigt definition was suggested to be named as “transitivity” in order to avoid confusion.
> "Transitivity" specifically refers to Barrat's and Weigt's definition.
correct. that is clear by the mentioned papers.
> Barrat's and Weigt's definition seems to be predominant, and there are places where "global clustering coefficient" is plainly taken as the same as transitivity, leaving Watt's and Strogatz's original definition as an "alternative" (remarkably in the Wikipedia article <https://en.wikipedia.org/wiki/Clustering_coefficient#Global_clustering_coefficient>, cf. also its discussion page <https://en.wikipedia.org/wiki/Talk:Clustering_coefficient#Global_clustering_coefficient_vs._Transitivity_ratio>).
wikipedia is subject to change. we should the references of scientific literature (as it is) and it would be fine and clear.
> LightGraphs.jl seems to take that view, such that its code of global_culstering_coefficient <https://github.com/JuliaGraphs/LightGraphs.jl/blob/1c6cf65cc0981250e430bbef39055da23bd25bd0/src/community/clustering.jl#L143-L159> implements Barrat's and Weight's definition (i.e. the so-called transitivity, although it does not use that name).
I’m not familiar with LightGraphs.jl. In my opinion, it would be better if they rename it to transitivity to be clear and avoid confusion.
> 
> If all that is correct, I'm afraid that the implementation and the docstring of transitivity in this package is quite a mess:
> 
> The function name implies that it should implement Barrat's and Weigt's definition.
Do you mean the function of LightGraphs.jl? If not, this function is correct, or not? Trans. is the Barrat's and Weigt's definition.
> However, the docstring seems to imply that it implements Watt's and Strogatz's definition (average of local clustering coefficient).
Yes, this is not really correct:
The network transitivity averages the local transitivity or clustering
coefficient
```math
\\mathcal{C} = \\frac{number of triangles including vertex i}{number of triples centred on vertex i}
```

but this is (almost) correct:
over the all nodes in the network [^Boccaletti2006]:
```math
\\mathcal{T} = \\frac{trace(R^3)}{\\sum R^2}
```
here, in the denominator the factor (1-\delta) is missing (as it should be corresponding to Eq (11) in Donner 2011). I’m sorry that I had overseen this.
> Nevertheless, the formula that it uses looks like being meant to calculate Barrat's and Weigt's definition.
see above.
> But the denominator is wrong, so it doesn't calculate any of them!
correct. But in Donner 2011 it is correct. And this is what we have found out already in previous emails.
> Now, fixing the code of the function to give the correct result as by Barrat and Weigt is the easiest (just fix the denominator by subtracting the trace of R²). But what do we do about the rest?
> 
> Modify the description given in the docstring, removing the reference to the average of local clustering coefficient and giving Barrat's and Weigt's definition instead?

the references are correct! there is simply one sentence and one equation wrong. The equation has to be used as in Donner 2011.

instead of "The network transitivity averages the local transitivity or clustering coefficient” you could write

"The network transitivity measures the fraction of closed triangles with respect to the number of linked triples of vertices in the whole network.”

Moreover, I suggest to slightly modify the verbatim copied sentence
“Consequently, characterising the degree of transitivity (or, alternatively, the relative frequency of closed 3-loops, which are commonly referred to as triangles) with respect to some individual vertex or the whole network provides important information on the structural graph properties, which may be related to important general features of the underlying system.”

to
“Consequently, characterising the degree of transitivity (or, alternatively, the relative frequency of closed 3-loops, which are commonly referred to as triangles) with respect to … the whole network provides important information on the structural graph properties, which may be related to important general features of the underlying system.”

(removing "some individual vertex or”)

This would help to avoid confusion.
> Give both definitions, and extend the function to allow the user choose between them?
transitivity is enough.
> Since we are planning to add the functions from LightGraphs.jl, as a quick fix while that is ready I'd suggest the simplest solution, i.e. the first one.
> 
> 
yes, this is fine.

and thank you very much for carefully checking this!

**Comment by hkraemer** [comment]
aggree and thanks!!

**Comment by heliosdrm** [comment]
Thanks Norbert for your clarifications. I have done all those changes in #110 .

In addition, as soon as the possibility of creating `SimpleGraph` objects from recurrence matrices is implemented, I'd suggest to deprecate the method `transitivity(R::AbstractRecurrenceMatrix)` in favor of `transitivity(SimpleGraph(R))`. The intermediate step required for creating the graph would be helpful for various things:

* Using the functions of LightGraphs directly, which are comprehensive, optimized and well-tested, not only for transitivity but for other parameters not yet implemented in this package.
* Controlling the characteristics of the recurrence network. For instance, recurrence matrices include diagonal points, but the adjacency matrices that characterize the network do not (vertices are not self-connected). The constructors of `SimpleGraph` etc. can handle this nicely.

**Comment by pucicu** [comment]
> In addition, as soon as the possibility of creating SimpleGraph objects from recurrence matrices is implemented, I'd suggest to deprecate the method transitivity(R::AbstractRecurrenceMatrix) in favor of transitivity(SimpleGraph(R)). The intermediate step required for creating the graph would be helpful for various things:
> 
> Using the functions of LightGraphs directly, which are comprehensive, optimized and well-tested, not only for transitivity but for other parameters not yet implemented in this package.
this sound very exciting! I agree with this strategy!

> Controlling the characteristics of the recurrence network. For instance, recurrence matrices include diagonal points, but the adjacency matrices that characterize the network do not (vertices are not self-connected). The constructors of SimpleGraph etc. can handle this nicely.
I’m not sure what you mean. RPs have diagonal lines. the RQA measures quantify these diagonal lines, but the network measures are independent of the timing, i.e., do not consider the “diagonality" of structures in the RP. shuffling a RP would destroy the temporal correlation and affects the RQA measures but not the network measures. Did you mean this or did you have something else in your mind?

**Comment by heliosdrm** [comment]
> I’m not sure what you mean. RPs have diagonal lines. the RQA measures quantify these diagonal lines, but the network measures are independent of the timing, i.e., do not consider the “diagonality" of structures in the RP. shuffling a RP would destroy the temporal correlation and affects the RQA measures but not the network measures. Did you mean this or did you have something else in your mind?

Sorry for my sloppy wording: I was commenting on the *main diagonal* of the matrix, i.e. the LOI. If you apply the formula of transitivity directly to the matrix of a RP, it will calculate it as if the vertices were self-connected, because the points of the LOI in a RP are nonzero. The calculation should be done using the adjacency matrix, which is the RP without the LOI. This is what I mean that could be done by default when the recurrence matrix is transformed into a `SimpleGraph` object, before calculating transitivity or other network parameters.

**Comment by pucicu** [comment]
yes, this is correct. 👍
