### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/RecurrenceAnalysis.jl#11]
Hey @heliosdrm ,

I will be writing the documentation page of RecurrenceAnalysis this week, and finalize #9 ! But since I am not super familiar with all the methods, I was wondering whether you could suggest a structure for the doc pages.

I intend to use the material of the README file and simply add the documentation strings as well as runnable examples. Can you suggest some thematic structure, as in which pages will contain what, etc.? For example `ChaosTools` is structured like this: https://juliadynamics.github.io/DynamicalSystems.jl/latest/chaos/overview/

**Comment by Datseris** [comment]
Could you also suggest a "standard" textbook for this field? The [wikipedia page](https://en.wikipedia.org/wiki/Recurrence_quantification_analysis) is at the moment in a bad state, it uses symbols without explaining them and acronyms without defining them...

**Comment by pucicu** [comment]
Hi George,

I’m a bit surprised about your comment. Which acronyms and symbols are not explained? I would be happy to improve the Wikipedia page (I had created this one years ago) in order to satisfy you. 😁

There is no book about RP and RQA but a review paper:

Marwan, N., Romano, M. C. ,Thiel, M. ,Kurths, J. (2007). "Recurrence Plots for the Analysis of Complex Systems". Physics Reports. 438 (5–6): 237

I really appreciate your efforts with the Julia package! Great work!

Best wishes
Norbert

**Comment by Datseris** [comment]
Hi Norbert,

well, thank you very much for your kind words, although _this_ Julia package is 100% the work of Helios! I can't take any credit for it!

I also want to apologize for my harsh judgement: I have now read the wikipedia page in much mroe detail. I was sloppy going over the [Background](https://en.wikipedia.org/wiki/Recurrence_quantification_analysis#Background) section of the page, and thus I completely missed that there is an entirely different and dedicated page for [Recurrence Plots](https://en.wikipedia.org/wiki/Recurrence_plot). The symbol **R**(i,j) is defined in that page, even though it is _not_ defiend in the main [RQA](https://en.wikipedia.org/wiki/Recurrence_quantification_analysis#RQA_measures) page. This was the missing symbol I was referring to, the other being the acronym LOI which is also defined on the introduction section (which I sloppily skipped).

Thank you for the citation, I will link it in the documentation page, along with the wiki page. 

As for improving the wikipedia page, here are my suggestions:
* Either merge the Recurrence plots page with the RQA one, or have a more detailed mention to recurrence plots in the latter page, preferably including a figure of a timeseries with its recurrence plot.
* Include the definition of the recurrence matrix in the RQA page.
* Maybe consider not defining the acronyms in the introduction section (which besides myself, other people also skip)
* (This one is strictly from my personal experience): P(\ell) is the counting function, right? It counts how many instances there are with length \ell . Although the wording frequency distribution is valid, maybe mention in parenthesis something like: "it counts how many instances have length \ell" ?

best,
George

**Comment by heliosdrm** [comment]
> Could you also suggest a "standard" textbook or review article for this field? 

Norbert already quoted a paper, but there is also this very recommendable book:
https://link.springer.com/book/10.1007/978-3-319-07155-8

I'll look on this issue in the next few days

**Comment by pucicu** [comment]
Yes, you can also cite this book, although it is more a collection of studies and not a text book I would use for teaching.
For nonlinear time series analysis I would suggest to cite the book by Kantz & Schreiber:
https://www.cambridge.org/core/books/nonlinear-time-series-analysis/519783E4E8A2C3DCD4641E42765309C7 <https://www.cambridge.org/core/books/nonlinear-time-series-analysis/519783E4E8A2C3DCD4641E42765309C7>

**Comment by Datseris** [comment]
@heliosdrm Don't worry about this so much at the moment, I've finished the documentation pages: https://github.com/JuliaDynamics/DynamicalSystems.jl/pull/81 

At the moment I have trouble actually building the documentation, but I hope I can resolve this soon. Then you can look the built documentation online and give me some feedback :) 

I'll post an update once I have managed to build the docs...

**Comment by Datseris** [comment]
Woohoo! Thankfully Travis is smarter than me since it managed to build the documentation: https://juliadynamics.github.io/DynamicalSystems.jl/latest/rqa/rplots/

**Comment by heliosdrm** [comment]
Awesome work! Thanks @Datseris !
Nothing to change in the documentation from my side. Now I guess we should "clean up" the README.md to make it like the other packages in JuliaDynamics (and update the broken badges, still pointing to the "heliosdrm" pages).

Marginally related issue: I see that the RQA `entropy` function is not exported anymore. I understand that the name may conflict with a less specific `entropy` function used in other packages of JuliaDynamics. But wouldn't be better to add an alias, e.g. `rqaentropy` or similar?

**Comment by finmod** [comment]
@Datseris and @heliosdrm 
For the documentation and examples, can I suggest (http://www.recurrence-plot.tk/) that has just about everything about RP and RQA including mentioning Recurrent Analysis.jl in the software section.

**Comment by Datseris** [comment]
@heliosdrm awesome! glad you like it. Yeap these changes should be done! I'll update the badges and add an Appveyor badge as well.

> Marginally related issue: I see that the RQA entropy function is not exported anymore. I understand that the name may conflict with a less specific entropy function used in other packages of JuliaDynamics. But wouldn't be better to add an alias, e.g. `rqaentropy` or similar?

Ops, sorry I was sloppy. I thought that this `entropy` was computing the shannon entropy, which you can get from `genentropy`. I now realize the mistake. Yeah, it should be renamed into `rqaentropy` and be exported and added to the docpages as well. Could you please do that while I reform README and badges?

@finmod thank you very much for the link I'll add a section of "other software" or something along those lines and also cite the codebase of Norbert.
