### ISSUE TITLE
Question on best place to allow modification to condition for recurrence.

### ISSUE THREAD

**Issue by rs7q5** [JuliaDynamics/RecurrenceAnalysis.jl#121]
I am working on creating a symbolic recurrence plot to add color to the recurrences. Essentially I just want it so a 1 only occurs when `x[i]=y[j]= some value`. I am just not sure if it makes more sense to just rewrite `recurrence_matrix` with this command and add an extra keyword to allow for a custom metric to be applied or if I need to create a brand new `RecurrenceMatrix` type. Or do I just need to modify get metric?

I currently have a very rough work around, but a majority of what I have coded is all the same that is already in this package besides a few lines, but I have not gotten to the analysis yet and a lot of the low level functions in rqa are still applicable. 

Solving #92 I think would also solve my problem though too.

**Comment by Datseris** [comment]
Nope. Just add the propagation `rqa(R::ARM) = rqa(R.data)` and make the original function `rqa` accept a sparce matrix.

**Comment by rs7q5** [comment]
I tried that, but doing that does not necessary pass all tests. I think I have a work around though that does pass tests and should let you just pass sparse  matrix through. will submit a PR shortly.
