### ISSUE TITLE
What's wrong with Windows x86?

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#15]
Appveyor fails for the x86 versions. No idea of what's happening there.

**Comment by Datseris** [comment]
Yeah, there is a problem with the sparce matrices... You can see the error log here: https://ci.appveyor.com/project/JuliaDynamics/recurrenceanalysis-jl/branch/master/job/ny4vad40m5ks96yk#L74 Seems like this is a Base problem...?

**Comment by Datseris** [comment]
Ah its on the `gmi` tests anyway. I'll remove them since we are moving this functionality to DelayEmbeddings.
