### ISSUE TITLE
Dedicated types for Recurrence matrices

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/RecurrenceAnalysis.jl#21]
as discussed in #20 having dedicated types RecurrenceMatrix, CrossRecurrenceMatrix etc, all of which are subtypes of AbstractRecurrenceMatrix has a lot of benefits. Let's discuss the implementation here.

1. What _type_ parameters should be there, besides the ones of the data field?
2. Any other fields besides the data field?

---

To-dos:

- [ ] Create types
- [ ] Ensure `recurrencematrix` and co return the types
- [ ] Enforce that the user is passing a recurrence matrix to e.g. laminarity, because the dispatch happens on ::AbstractRecurrenceMatrix (so far there is no guarantee that x is not a unfitting matrix)
- [ ] Pretty printing (which I super love). So when the user sees x they will get info that it is a recurrence matrix, etc. This is really cool for front end users!

**Comment by Datseris** [comment]
I am opening a branch for this. At the moment I do not see any reason for recurrence and cross recurrence matrices to be of different type. I will make a datastructure that is simply called `RecurrenceMatrix` and has one field the data and the other field the type, simply as a string: `cross-`,`joint-` or the empty string.

**Comment by heliosdrm** [comment]
I see your point about the recipe. Then, I think that the best is to keep the original approach: the types will be `RecurrenceMatrix`, etc. (I would not call `xxxPlot` to something that is not directly plottable).

Then, the question is about the name of the function to create the plottable matrix. Shall we keep `recurrenceplot`, or change it to `plottable`?

I'm opening a new issue about the other question (different types for recurrence and cross-recurrence matrices). This is related to your latest question in #20.

**Comment by Datseris** [comment]
Closed in #25
