### ISSUE TITLE
Extension of RQA and CRQA to trajectories

### ISSUE THREAD

**Issue by finmod** [JuliaDynamics/RecurrenceAnalysis.jl#29]
@heliosdrm Just wanted to bring to your attention this extension to trajectories (in the DynamicalSystems sense) i.e. multidimensional timeseries of RecurrenceAnalysis. (https://www.frontiersin.org/articles/10.3389/fpsyg.2016.01835/full)

The illustration with Lorenz63 demonstrates the usefulness of the trajectory approach versus the timeseries approach.

**Comment by heliosdrm** [comment]
Thanks. If your suggestion is to add support for the analysis of trajectories, I think that this is already done, unless there is something more implicit in the idea (I confess that I have not yet read the paper in depth).

The functions `embed` and `reconstruct` (now imported from [DelayEmbeddings](https://github.com/JuliaDynamics/DelayEmbeddings.jl)) can be applied to multidimensional variables. The creation and analysis of recurrence plots do not "care" if the data set is reconstructed from a one-dimensional time series, or if it is a trajectory in origin.

**Comment by Datseris** [comment]
Yeap, all RQA functions can accept a `Dataset` (which is a trajectory _or_ an embedded timeseries). I'll close this for now, will re-open if we have misunderstood.

**Comment by finmod** [comment]
Excellent. This is a strength of Dataset and of the new DelayEmbeddings that should be emphasized in the docs and in the examples by showing that RecurrenceAnalysis is multidimensional.
