### ISSUE TITLE
deprecation of `crossrecurrencematrix`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#33]
`recurrencematrix`, `crossrecurrencematrix` and `jointrecurrencematrix` are deprecated in favor of the type constructors `RecurrenceMatrix`, etc. But `crossrecurrencematrix` is still used internally to create the `data` field (i.e. the actual matrix).

This is a bit confusing. Should we change the name of that internal function?

**Comment by Datseris** [comment]
I've changed the name just now. I think the current state is okay, let me know if you disagree.
