### ISSUE TITLE
names of RQA functions

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#34]
After some discussion in #24 I propose the following changes in the names of the functions for RQA. It means deprecating three of the older names, and adding a couple of parameters that I have not actually seen reported in papers, like the entropy of vertical lines or the longest recurrence time. But the advantage is that the set of functions and their names follow a more systematic pattern, easier to remember. This is what [pyunicorn](http://www.pik-potsdam.de/~donges/pyunicorn/) and [PyRQA](https://pypi.org/project/PyRQA/) also do, so it facilitates understanding for users of both Python and Julia.

(Each function name is accompanied by the key of the corresponding dictionary item returned by `rqa` in square brackets.)

These conventional names remain without changes:

* `recurrencerate` [`"RR"`]
* `determinism` [`"DET"`]
* `divergence` [`"DIV`"]
* `laminarity` [`"LAM"`]
* `trappingtime` [`"TT"`]
* `trend` [`"TND"`]

In addition, diagonal lines, vertical lines and recurrence times will have functions to calculate their mean and maximum value, and their (Shannon) entropy, with the following common pattern (this may be nicely meta-programmed):

For diagonal lines:

* `dl_average` [`"L"`] (deprecates `avgdiag`)
* `dl_max` [`"Lmax"`] (deprecates `maxdiag`)
* `dl_entropy` [`"ENT"`] (deprecates `rqaentropy`)

For vertical lines:

* `vl_average` (equivalent to `trappingtime`, which will remain)
* `vl_max` [`"Vmax"`] (deprecates `maxdiag`)
* `vl_entropy` [`"VENT"`]

For recurrence times (all new)

* `rt_average` [`"MRT"`] (with alias `meanrecurrencetime`", as reported in some papers)
* `rt_max` [`"RTmax"`]
* `rt_entropy` [`"RTENT"`]

Also add `nmprt` (with key `"NMPRT"`] for the number of the most probable recurrence time.

There are some keys that vary across sources. Namely, Norbert's paper (2007) uses "ENTR" and "TREND", where the RQA book of 2015 uses "ENT" and "TND". I have followed the latter, which are shorter, but we are now on time to change it.

(I'm also closing #30, which is redundant with this)

**Comment by pucicu** [comment]
I agree with these names. No problem with “ENT” instead of “ENTR” etc. Very nice!

**Comment by Datseris** [comment]
Excellent I fully agree.

Only on the final point, I vote on `ENT` and `TREND`. `TND` does not have `R` in it, I would never take it as "trend". The r in the trend is quite strong when used verbally.
