### ISSUE TITLE
[Doc] Theiler = 0

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/RecurrenceAnalysis.jl#45]
Does the value of `0` for the theiler window exclude the LOI or it includes it?

**Comment by heliosdrm** [comment]
`theiler=0` means that the LOI is *included*.

You can see it as if the parameter `theiler` indicates:

(a) how many diagonals are excluded (starting from the main diagonal, and proceeding symmetrically), or
(b) which is the minimum index of the diagonals that are included (considering that `diag(x,0)` is the main diagonal.

**Comment by Datseris** [comment]
But the LOI has to be somehow excluded from the diagonal length computation right? because then for a standard RecurrenceMatrix the `dl_max` is just the size of the matrix. On the other hand, it has to be re-included if it is a CrossRecurrenceMatrix because you want to count diagonals that may fall on the identity line.

How does this work currently?

**Comment by heliosdrm** [comment]
Yes, in the analysis of recurrence matrices (and joint recurrence matrices) the LOI is usually excluded, whereas in cross recurrence matrices it is included. In the older version of the package (before creating the specific types) there was no possibility to distinguish between both cases, so the default `theiler=0` was applied to all.

Now it's easier to provide a default Theiler window conditioned to the type of the matrix, but I'm not totally sure about it. The main advantage is for the "lazy" user or the absolute beginner, who might obtain usual results with the simplest function call. But there is a couple of disadvantages:

1. Changing the default parameters between methods of the same function may be confusing. Take the following example:

```
m1 = RecurrenceMatrix(x,ε)
m2 = CrossRecurrenceMatrix(x,x,ε)

# Lots of things are done in the meantime, and then,
# when I forgot how `m1` and `m2` where created ...

m1 == m2                                 # true, see PR #
recurrencerate(m1) == recurrencerate(m2) # false!!! what...?!
```

2. The purpose of the Theiler window is to rule out self-recurrences, but in many cases (e.g. high sampling rate) such self-recurrences will extend to various data points, and a window greater than 1 will be necessary. I think that a specific default `theiler=1` for `RecurrenceMatrix` would invite to be less careful about this than a general `theiler=0` ("ok, the self-recurrences are automatically handled, so let the function do the magic"). Or put it another way, such specific default will have to be overriden by a user-defined window in many cases, so it's not that beneficial.

All in all, although this common default is a "legacy" limitation, I think that it is not bad.


For what is worth, this is what other popular packages that support CRPs do:

* CRP Toolbox (Matlab): LOI excluded by default in RPs and JRPs. Theiler window defined by the user.
* crqa (R): No diagonal excluded by default. Theiler window defined by the user.
* pyunicorn (Python): No diagonal excluded. No support for Theiler window.

**Comment by Datseris** [comment]
@heliosdrm  I am still confused so I have a quick question first: What value do I have to give to `theiler` to _exclude_ the LOI? Is it possible to exclude it? If `theiler = 0` means it is already included, how can I exclude it?

**Comment by heliosdrm** [comment]
* `theiler=0` means that the whole matrix is scanned for lines
* `theiler=1` means that the LOI is excluded
* In general, `theiler=n` means that the `n` central diagonals are excluded (at both sides of the LOI, i.e. actually `2n-1` diagonals are excluded).

Regarding `m1 == m2`, I would keep it `true`, because `==` does not generally test equality of the type, but of the data "content"; e.g. `1.0 == 1 == 1+0im`, etc.

**Comment by Datseris** [comment]
From #20 : 

I have written:

> theiler : I believe the value 1 is a better default. As you said for cases where there are actually diagonal entries around the main diagonal one has to exclude more than just the LOI. So neither 0 or 1 are enough of a "good" value. On the other side, in cases where there aren't any diagonals the LOI still exists for RecurrenceMatrix and thus could/should be excluded by default.

**Comment by heliosdrm** [comment]
Do you mean dispatch on `RecurrenceMatrix` and `JointRecurrenceMatrix`with `theiler=1`, but on `RecurrenceRate` with `theiler=0` ?

**Comment by Datseris** [comment]
`RecurrenceRate` ? You mean `recurrencerate` ? But that this is a function, how do you mean "dispatch" here? Sorry I got confused :D 

I meant that the default value of `theiler` is 1 everywhere instead of 0 everywhere.

**Comment by heliosdrm** [comment]
Sorry, my bad. I meant `CrossRecurrenceMatrix`, don't know what I was thinking on.

But `theiler=1` for `CrossRecurrenceMatrix` I think is worse than `theiler=0` for the other... I mean, in an analysis of a recurrence plot that includes the LOI you know what happens (there is an extra line through the main diagonal). In the analysis of a cross-recurrence plot without the LOI you never know what are you losing.

**Comment by Datseris** [comment]
Hm, I see. Then I urge you to reconsider your prohibition of different default `theiler` values for different types.

I suggest default of 1 for Recurrence & JointRecurrence and default of 0 for CrossRecurrence.

I know that you have made the argument:
```
m1 = RecurrenceMatrix(x,ε)
m2 = CrossRecurrenceMatrix(x,x,ε)

# Lots of things are done in the meantime, and then,
# when I forgot how `m1` and `m2` where created ...

m1 == m2                                 # true, see PR #36
recurrencerate(m1) == recurrencerate(m2) # false!!! what...?!
```
but I don't think "I forgot how `m1` and `m2` are created" is strong enough of an argument.

One should not sacrifice good decisions to counteract user sloppyness. The user should not be sloppy in the first place. It is a mandatory agreement for any user of `RecurrenceAnalysis` that they have read the documentation and thus have seen that `theiler` has type-dependent defaults (_if_ we change it).

**Comment by heliosdrm** [comment]
After sleeping over it, I'm more inclined to implement the conditional Theiler window.

 I'll work on a PR to revise its implementation and documentation. But we should revise this together with #48, which is indirectly related.
