### ISSUE TITLE
Denominator of recurrence rate

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#48]
Now it is the size of the entire matrix. This is the simplest choice, and it is also coherent with the formula given in Norbert's 2007 paper, which is the most popular reference for RQA (*Phys. Reports* 438:237-329).

However, when a Theiler window is applied, it might also make sense to reduce the denominator, since there are less points that may be detected as recurrences. Actually the formula in the first chapter of the RQA book from 2015 has *N(N-1)* in the denominator, accounting for the exclusion of the *N* points of the LOI. 

Matlab's CRP Toolbox does adjust the denominator according to the Theiler window. Other packages that I know don't, e.g. [crqa](https://cran.r-project.org/package=crqa) or [PyRQA](https://pypi.org/project/PyRQA/). (I'm not counting pyunicorn, because that package just doesn't have the option of setting a Theiler window).

See also the discussion here:
http://www.recurrence-plot.tk/forum/viewtopic.php?f=3&t=4641&sid=1e67d4c05d5d81297ce5888d8a305705

**Comment by heliosdrm** [comment]
If we make `theiler=1` the default for RPs and JRPs, I'd think twice about using the "full" denominator `n^2`. It is the formula in some popular references (including http://www.recurrence-plot.tk/rqa.php), and the one implemented in various software packages, but with the default options even a flat time series would always have RR<1.

So, what to do?:

* Never mind, leave it as it is, simple and not that important for long time series.
* Always remove size of the Theiler window from the denominator.
* Only adjust the denominator only for RPs and JRPs (if making the default `theiler` different for them). In such case:
  + Remove the size of the Theiler window.
  + Remove only the size of the LOI (to match the formula in the RQA book).

**Comment by Datseris** [comment]
Unfortunately as I said I don't have the expertise to help with this decision... Maybe @pucicu can contribute here.

**Comment by pucicu** [comment]
When applying the Theiler window, the denominator should be corrected by this. I think, in the chapter in the RQA book, it was not given just for didactical reasons. In deed, it would be more correct to provide there the corrected denominator.

**Comment by heliosdrm** [comment]
Thanks. What adjustement you recommend?

(a) always reduce the denominator removing the number of points covered by the Theiler window, for any matrix?
(b) only adjust RPs and JRPs (leave CPRs) without denominator adjustment?

And if (b):
(b.1) reduce by the full extent of the Theiler window (same as (a), but excluding CPRs)?
(b.2) reduce only by N points (the extent of the LOI), as in the formula RR=sum(r)/(N(N-1)), for whatever Theiler window greater than zero?

**Comment by pucicu** [comment]
Haha, good point. Obviously I forgot what I wrote in the forum …
But at the moment, I would say removing the Theiler window also from the denominator would make more sense.

The point is, we should test this on some prototypical ans also real world examples. But I don’t have the time to do it.

**Comment by pucicu** [comment]
I think b.1 makes most sense.

for CRPs it would not make sense to apply a Theiler window because there isn't a LOI.
