### ISSUE TITLE
`lmin` in `recurrencestructures`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#49]
I acknowledge a bit of inconsistency here: the default `lmin` in RQA functions is 2. But when I wrote `recurrencestructures` I set `lmin=1` there. Why?

For the diagonal and vertical histograms, `lmin=n` makes zero the values of the `(n-1)` first bins. The rest is the same. Thus, I initially thought that the default `lmin=2` was not very useful, it just removed some information.

However, the story is different when recurrence times are also counted: ruling out lines shorter than `lmin` means that sets of recurrence times between isolated points are merged in a smaller number of longer recurrence times. So for recurrence times changing `lmin` means more than just "deleting" or ignoring some part of the output.

All in all, I agree that a consistent `lmin=2` everywhere is preferable.

An alternative would be to give always the "full" diagonal and vertical line histograms, and just use `lmin` for the calculation of recurrence times. The disadvantage is that this means calculating the vertical histograms twice.

I'm debating myself, don't know what is the best.

**Comment by pucicu** [comment]
Hi Helios,

for the histogram, the l_min should not be necessary. Only for the measures like DET, LAM etc. For the recurrence times, I think, it is not necessary to have a l_min at all. Why should it be useful there?

Best
Norbert

**Comment by heliosdrm** [comment]
I agree with ignoring `lmin` for diagonal and vertical histograms.

In recurrence times the `lmin` is relevant (as it is coded now). Take the following line of a recurrence matrix (`x` is a recurrent point, `·` is a blank point):

```
· · · x · · · x x · · x · · · x · · x x · · · · x
      |--  4 --|-- 3--|-- 3 --|-- 3--|--   5  --|
```
There the histogram of recurrence times has 3 items of length==3, one item of length==4, and another of length==5 .

But if we rule out lines shorter than 2 points (i.e. isolated points, here marked with `o`):
```
· · · o · · · x x · · o · · · o · · x x · · · · o
               |--       11        --|
```

Then we only  have a long recurrence time of length==11.

So, changing `lmin` completely change the histogram of recurrence times, in a way that cannot be predicted by the value of `lmin` itself.

The only way that `lmin` would not affect the histogram of recurrence times, is if these were always counted considering all points (although in the count of vertical lines we do consider a minimum line length)

**Comment by pucicu** [comment]
OK, I haven’t considered it this way. It seems the concept of a minimal line is different here. Where for the “black” lines l_min is considered to be the minimal line length of a black line, for the recurrence times (which could be represented by the “white” vertical line – although it is not really this what you have implemented), the minimal line length is not the minimal recurrence time (white line) but a black line. Interesting concept and it seems to be worth to play a bit with this.

**Comment by heliosdrm** [comment]
After re-reading the papers, I have realized that recurrence times are defined as distances between recurrent points regardless of whether they are part of tangential motion or not. So the current implementation is wrong, or at least it does not do what the literature says.

The good news is that it is super-easy to solve: looking at the code, the condition to include/exclude a recurrence time in the histogram is not mixed with the condition to include/exclude a vertical line when it is found. So it is just a matter of removing some `if-else`s.

And moreover we'll solve the problem with `lmin`, by just ignoring it totally in `recurrencestructures. :smile:

**Comment by Datseris** [comment]
Is this the case where one uses *Two birds with one stone* ?:D
