### ISSUE TITLE
Performance regression due to new code of `trend`

### ISSUE THREAD

**Issue by heliosdrm** [JuliaDynamics/RecurrenceAnalysis.jl#57]
Part of the big improvement in speed that I saw in v1.0.0-alpha has been lost with the changes in `trend` (instead of a gain in time > 50% it is around 40%) . Changes are necessary because the calculations were wrong, but I want to look for a smarter, faster way of calculating it.

**Comment by Datseris** [comment]
For reference, the aforementioned changes were done in : https://github.com/JuliaDynamics/RecurrenceAnalysis.jl/pull/54

**Comment by heliosdrm** [comment]
And now it is fixed in #56 :smile:

With this last fix it is even faster than pyunicorn!!!
