### ISSUE TITLE
[DOC] Enrich RQA docstrings with comments for usefulness / understanding

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/RecurrenceAnalysis.jl#65]
I suggest that little by little we start enriching the docstrings of _all_ RQA functions by copy/pasting the relevant text from Norbert's book. This will really make the RQA page a "library" page (which is my life-long dream with **DynamicalSystems.jl**).

For example, in the `determinism` we can copy paste:

> Systems possessing deterministic (rule-obeying) dynamics are characterized by diagonal lines indicating repeating recurrences within a state. For periodic signals the diagonal lines are long. For chaotic signals the diagonal lines are short. For stochastic signals the diagonal lines are absent, save for chance recurrences forming very short lines. DET can be interpreted as the predictability of the system more so for periodic behaviors than chaotic processes. But it must be realized that DET does not have the same strict meaning of the determinism of a process. 

And so on and so forth.

**Comment by heliosdrm** [comment]
I like the "library" approach of DynamicalSystems.jl. Nevertheless we should take care about how much we copy from a single source if it doesn't have an open license; we don't want to make Norbert's editors angry. :smile:

**Comment by pucicu** [comment]
I could also have a final look or prepare something if you like.

**Comment by Datseris** [comment]
I think this is solved now, since quite a lot of time actually...

**Comment by Datseris** [comment]
https://juliadynamics.github.io/DynamicalSystems.jl/dev/rqa/quantification/#classical-rqa-measures
