### ISSUE TITLE
Citation of RecurrenceAnalysis

### ISSUE THREAD

**Issue by felixcremer** [JuliaDynamics/RecurrenceAnalysis.jl#75]
What is the best way to cite RecurrenceAnalysis.jl?
I have seen the Citation of DynamicalSystems.jl, but is this also applicable for this package?
Could you provide a CITATION.bib file for RecurrenceAnalysis.jl?

**Comment by Datseris** [comment]
Hey there.

I don't think there is a paper associated with RecurrenceAnalysis.jl specifically.

Let's ask @heliosdrm to confirm.

Since it is part of DynamicalSystems.jl then you can indeed safely cite that one:
```
@article{Datseris2018,
  doi = {10.21105/joss.00598},
  url = {https://doi.org/10.21105/joss.00598},
  year  = {2018},
  month = {mar},
  volume = {3},
  number = {23},
  pages = {598},
  author = {George Datseris},
  title = {DynamicalSystems.jl: A Julia software library for chaos and nonlinear dynamics},
  journal = {Journal of Open Source Software}
}
```
I'll put CITATION.bib in the repos in the meantime.

**Comment by heliosdrm** [comment]
Hi, I confirm: there is no paper to cite yet. But it's a good idea to work on!
