### ISSUE TITLE
divergence in perpendicular recurrence plot : estimating lyapunov exponents

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/RecurrenceAnalysis.jl#78]
This paper : https://www.sciencedirect.com/science/article/abs/pii/S0375960199007513?via%3Dihub 

discusses of a way to compute the maximum Lyapunov exponent from an RP using what the authors call "divergence in perpendicular recurrence plot ".

Seems to be useful and nicely ties with the other method we have to estimate λ from timeseries in **DynamicalSystems.jl**

**Comment by pucicu** [comment]
Unfortunately, the authors have not explained how to determine whether a state is perpendicular to a trajectory. It cannot be a strict criterion as it would be almost impossible for a discretized system to get the perpendicular states. At least, we were unable to get reasonable results. We also shortly noted this in our latest paper: https://doi.org/10.1016/j.physleta.2019.125977 <https://doi.org/10.1016/j.physleta.2019.125977>

**Comment by Datseris** [comment]
Based on your reply, I think that it is then not worth it to attempt to implement this DPRP
