### ISSUE TITLE
Plot recipes

### ISSUE THREAD

**Issue by asinghvi17** [JuliaDynamics/RecurrenceAnalysis.jl#80]
Any plans for Plots.jl?  Would be happy to help.

**Comment by Datseris** [comment]
No, not really. All plotting is done via converting `RecurrenceMatrix` to plottable data, using the functions `recurrenceplot, coordinates, grayscale`.

But if you want a recipe you can go ahead and PR, I don't think anyone will say no :P

**Comment by asinghvi17** [comment]
I think that just a scatter plot using `coordinates` should be fine.   Plots may choke with large numbers of elements; Makie should be fine, though, if you use `spy` on the sparse matrix.  Note that since OpenGL does not accept booleans-as-numbers, you need to plot `SparseMatrixCSC{Int64, Int64}(rmat.data)`
